services:
  web:
    image: diddle:latest
    build: .
    environment:
      BASE_URL: http://localhost:8000
      DB_PATH: /db/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db
